<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.3700" tests="13" failures="6">
  <testsuite name="Root Suite" timestamp="2023-04-04T18:09:41" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="stock_trades_api_medium" timestamp="2023-04-04T18:09:41" tests="13" file="/projects/challenge/test/index.spec.js" time="0.3700" failures="6">
    <testcase name="stock_trades_api_medium should create a new trade of buy type" time="0.0610" classname="should create a new trade of buy type">
    </testcase>
    <testcase name="stock_trades_api_medium should create a new trade of sell type" time="0.0080" classname="should create a new trade of sell type">
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all the trades" time="0.0560" classname="should fetch all the trades">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
    at Context.<anonymous> (test/index.spec.js:85:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch no trades if the type filter value does not exist" time="0.0470" classname="should fetch no trades if the type filter value does not exist">
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all trades for a user" time="0.0410" classname="should fetch all trades for a user">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
    at Context.<anonymous> (test/index.spec.js:99:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch no trades if user filter value does not exist" time="0.0370" classname="should fetch no trades if user filter value does not exist">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
    at Context.<anonymous> (test/index.spec.js:106:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all buy trades for a user" time="0.0260" classname="should fetch all buy trades for a user">
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all sell trades for a user" time="0.0240" classname="should fetch all sell trades for a user">
      <failure message="expected [ Array(3) ] to deeply equal [ Array(1) ]" type="AssertionError"><![CDATA[AssertionError: expected [ Array(3) ] to deeply equal [ Array(1) ]
    at Context.<anonymous> (test/index.spec.js:121:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch a single trade" time="0.0110" classname="should fetch a single trade">
    </testcase>
    <testcase name="stock_trades_api_medium should get 404 if the trade ID does not exist" time="0.0100" classname="should get 404 if the trade ID does not exist">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 404 but got 400" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 404 but got 400
    at Context.<anonymous> (test/index.spec.js:133:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a put request to /trades/:id" time="0.0130" classname="should get 405 for a put request to /trades/:id">
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a patch request to /trades/:id" time="0.0220" classname="should get 405 for a patch request to /trades/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404
    at Context.<anonymous> (test/index.spec.js:146:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a delete request to /trades/:id" time="0.0140" classname="should get 405 for a delete request to /trades/:id">
    </testcase>
  </testsuite>
</testsuites>