<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.3210" tests="13" failures="11">
  <testsuite name="Root Suite" timestamp="2023-04-04T17:48:05" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="stock_trades_api_medium" timestamp="2023-04-04T17:48:05" tests="13" file="/projects/challenge/test/index.spec.js" time="0.3210" failures="11">
    <testcase name="stock_trades_api_medium should create a new trade of buy type" time="0.0760" classname="should create a new trade of buy type">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 200" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 200
    at Context.<anonymous> (test/index.spec.js:70:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should create a new trade of sell type" time="0.0110" classname="should create a new trade of sell type">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 200" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 200
    at Context.<anonymous> (test/index.spec.js:77:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all the trades" time="0.0410" classname="should fetch all the trades">
    </testcase>
    <testcase name="stock_trades_api_medium should fetch no trades if the type filter value does not exist" time="0.0260" classname="should fetch no trades if the type filter value does not exist">
      <failure message="expected [ Array(4) ] to deeply equal []" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal []
    at Context.<anonymous> (test/index.spec.js:93:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all trades for a user" time="0.0230" classname="should fetch all trades for a user">
      <failure message="expected [ Array(4) ] to deeply equal [ Array(2) ]" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal [ Array(2) ]
    at Context.<anonymous> (test/index.spec.js:100:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch no trades if user filter value does not exist" time="0.0230" classname="should fetch no trades if user filter value does not exist">
      <failure message="expected [ Array(4) ] to deeply equal []" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal []
    at Context.<anonymous> (test/index.spec.js:107:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all buy trades for a user" time="0.0240" classname="should fetch all buy trades for a user">
      <failure message="expected [ Array(4) ] to deeply equal [ Array(1) ]" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal [ Array(1) ]
    at Context.<anonymous> (test/index.spec.js:114:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all sell trades for a user" time="0.0260" classname="should fetch all sell trades for a user">
      <failure message="expected [ Array(4) ] to deeply equal [ Array(1) ]" type="AssertionError"><![CDATA[AssertionError: expected [ Array(4) ] to deeply equal [ Array(1) ]
    at Context.<anonymous> (test/index.spec.js:121:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch a single trade" time="0.0130" classname="should fetch a single trade">
    </testcase>
    <testcase name="stock_trades_api_medium should get 404 if the trade ID does not exist" time="0.0060" classname="should get 404 if the trade ID does not exist">
      <failure message="expected &apos;Trade not found&apos; to deeply equal &apos;ID not found&apos;" type="AssertionError"><![CDATA[AssertionError: expected 'Trade not found' to deeply equal 'ID not found'
    at Context.<anonymous> (test/index.spec.js:134:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a put request to /trades/:id" time="0.0170" classname="should get 405 for a put request to /trades/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404
    at Context.<anonymous> (test/index.spec.js:140:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a patch request to /trades/:id" time="0.0190" classname="should get 405 for a patch request to /trades/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404
    at Context.<anonymous> (test/index.spec.js:146:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a delete request to /trades/:id" time="0.0160" classname="should get 405 for a delete request to /trades/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 204" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 204
    at Context.<anonymous> (test/index.spec.js:152:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)]]></failure>
    </testcase>
  </testsuite>
</testsuites>